spring:
  application:
    name: oauth2-service

server:
  port: 9999

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/